---
title: "BIOSTAT 615 Tom's Walkthrough"
author: "Thomas Cooper"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\exp_periods.R")
source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\Gp_calcs.R")
source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\secant_method.R")
source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\persondata_to_emission.R")
source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\simulate_data.R")

```

```{r}
#Lets look at some raw data

#Raw CO2 Concentration over time is too variable. Our Interval Average CO2 concentrations are a lot more smooth. Additionally,
#Where we have significant changes in the values of our average CO2 values, we have spikes in our interval CO2 variance. We
#can use these spikes as indicators for an exponential process. We can then move away from the spikes in the forwards and
#backwards directions. We can determine start / stop points by bounding the exponential interval at the points in which
#the slope deflects back across zero. If an exponential growth process, find where the slope becomes non-positive. If an
#exponential decay process, find where the slope becomes non-negative.

source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\Exponential_Periods_Rationale.R")

useful_data
```
```{r}
#Hold on, how do we determine the interval we average on? What we do is we use the Kolmogorov–Smirnov test to determine
#the minimum p-interval value to make the distribution of our slopes for our averaged CO2 values different from the
#raw CO2 slope distribution.

plot(data$`Time(dd/mm/yyyy)`, p_slope$base, xlab = "Time", ylab = "Slope Value", main = "Raw Data Slope Distribution")

plot(data$`Time(dd/mm/yyyy)`, p_slope[, paste(p)], xlab = "Time", ylab = "Slope Value", main = "Interval Average Slope Distribution, p = 10")

plot(data$`Time(dd/mm/yyyy)`, p_slope[, paste(p+1)], xlab = "Time", ylab = "Slope Value", main = "Interval Average Slope Distribution, p = 11")
```


```{r}
#Lets increase the quantile cutoff. This can help remove some unwanted periods that were picked up due to noise.

useful_data_2 = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, 0.95)

useful_data_2

useful_data_3 = exp_periods(data$`Time(dd/mm/yyyy)`, data$`Carbon dioxide(ppm)`, 0.97)

useful_data_3
```
```{r}
#It also works with simulated data!

source("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\Exponential_Periods_Rationale_simulated.R")

useful_data
```

```{r}
#Now we have our periods, lets try and estimate with secant method. Where should our initial guess be?
#Lets grab one of our exponential periods and some placeholder values for our arguments. Lets look at a plot
#of our objective function.

#Need to get the following:

#get our C0, t0, C1, t1. Just do the first growth start and stop indexes
C0 = data$`Carbon dioxide(ppm)`[useful_data[1,1]]
t0 = useful_data[1,4]
C1 = data$`Carbon dioxide(ppm)`[useful_data[1,2]]
t1 = useful_data[1,5]

#get our delta time value for the same indexes
delta_t = as.numeric(difftime(t1,t0), units = "hours")

#And just assign some placeholders. Will simplify the data used in the simulated data, as that is the data we are plotting
n = 2
Gp = Gp_rate(16.00 / 24)
Volume = 200

plot_vals = c()
for (i in seq(0.1,1,.01)){
  plot_vals = c(plot_vals, build_up(i, n, Gp, Volume, C0, C1, delta_t))
}

#First, get some useful info

aer_asymptote = secant_starter(NA, n, Gp, Volume, C0, C1, delta_t)$asymptote

aer_root = secant_method(NA, n, Gp, Volume, C0, C1, delta_t)$root


#Lets plot!
plot(seq(0.1,1,.01), plot_vals, ylab = "Objective Function Value", xlab = "Air Exchange Rate", main = "Objective function vs Air Exchange Rate", ylim = c(-100,100))
lines(c(aer_asymptote,aer_asymptote), c(-100, 1500), col = "red")
plot(seq(0.1,1,.01), plot_vals, ylim = c(-1,1), ylab = "Objective Function Value", xlab = "Air Exchange Rate", main = "Objective function vs Air Exchange Rate")
lines(c(0,1), c(0,0))
lines(c(aer_root,aer_root), c(-1, 1), col = "blue")
lines(c(aer_asymptote,aer_asymptote), c(-1, 1), col = "red")

#The red line represents the asymptote that will always be generated by this function
#The blue line represents where the function value is estimated to be zero
#The values of these can be determined using the secant_starter and secant_method fucntions

cat("Secant Starter Output. Start and Stop are the two starting points needed for the root finding secant method. Asymptote is the calculated asymptote of the objective function. Solving for the Air Exchange Rate and the Volume, Start and Stop will always be less than the asymptote. Solving for the number of people or the Gp value, Start and Stop will always be larger than the asymptote.\n")

secant_starter(NA, n, Gp, Volume, C0, C1, delta_t)
  
cat("-------------------\n")
cat("Secant Method Output. Secant Method will solve for the root of the build_up function and return the root value, the objective function  value at the root, the number of iterations of the secant method and if the method converged or not.\n")

secant_method(NA, n, Gp, Volume, C0, C1, delta_t)


#Lets also plot for the other variables, so you believe what I'm saying!
aer = aer_root

n_seq = seq(1.5,2.5,.01)
Gp_seq = seq(0.1,1,.01)
V_seq = seq(195,250,1)

plot_vals_n = c()
for (i in n_seq){
  plot_vals_n = c(plot_vals_n , build_up(aer, i, Gp, Volume, C0, C1, delta_t))
}

n_asymptote = secant_starter(aer, NA, Gp, Volume, C0, C1, delta_t)$asymptote

n_root = secant_method(aer, NA, Gp, Volume, C0, C1, delta_t)$root

plot_vals_Gp = c()
for (i in Gp_seq){
  plot_vals_Gp = c(plot_vals_Gp, build_up(aer, n, i, Volume, C0, C1, delta_t))
}

Gp_asymptote = secant_starter(aer, n, NA, Volume, C0, C1, delta_t)$asymptote

Gp_root = secant_method(aer, n, NA, Volume, C0, C1, delta_t)$root

plot_vals_V = c()
for (i in V_seq){
  plot_vals_V = c(plot_vals_V, build_up(aer, n, Gp, i, C0, C1, delta_t))
}

V_asymptote = secant_starter(aer, n, Gp, NA, C0, C1, delta_t)$asymptote

V_root = secant_method(aer, n, Gp, NA, C0, C1, delta_t)$root


#Lets plot!
plot(n_seq, plot_vals_n, ylim = c(-1,1), ylab = "Objective Function Value", xlab = "Population", main = "Objective function vs Population")
lines(c(1.5,2.5), c(0,0))
lines(c(n_root,n_root), c(-1, 1), col = "blue")
lines(c(n_asymptote,n_asymptote), c(-1, 1), col = "red")

plot(Gp_seq, plot_vals_Gp, ylim = c(-1,1), ylab = "Objective Function Value", xlab = "Gp value", main = "Objective function vs Gp")
lines(c(0,1), c(0,0))
lines(c(Gp_root,Gp_root), c(-1, 1), col = "blue")
lines(c(Gp_asymptote,Gp_asymptote), c(-1, 1), col = "red")

plot(V_seq, plot_vals_V, ylim = c(-1,1), ylab = "Objective Function Value", xlab = "Room Volume", main = "Objective function vs Room Volume")
lines(c(195,250), c(0,0))
lines(c(V_root,V_root), c(-1, 1), col = "blue")
lines(c(V_asymptote,V_asymptote), c(-1, 1), col = "red")


#If you are paying close attention, you might notice that the roots we found for n, Gp, and V are the same values
#of the initial placeholders we chose in the first place!
```

```{r}
# simulating data
# Let's start with "person data"

# simulated data for testing
# consider a 24 hour time period, starting at midnight and running until the following midnight
# We have 17 people enter at 8 am, leave for one hour at noon, and leave for the day at 5 pm
# 2 adults and 15 children
persondata <- data.frame(
  time = c(0, 8, 8, 12, 12, 13, 13, 17, 24),
  n = c(0, 15, 2, 0, 0, 15, 2, 0, 0),
  age = c(0, 8, 30, 8, 30, 8, 30, 0, 0),
  gender = rep(NA, 9),
  MET = c(NA, 3, 1.8, 3, 1.8, 3, 2, NA, NA),
  CO2rate = rep(NA, 9)
)

volume=500
envCO2=400
temp=25
Q=.1 # .1*3600/500 = .72 Air exchanges /hr
var = 1 #Variance parameter for CO2 readings

# Let's simulate data:
simulated.dat <- simulateData(persondata=persondata,
                              volume=volume,
                              ventilation_rate=Q,
                              CO2var=var,
                              freq=120)

# Let's get Gp values for each time point in our simulation
emissions <- persondata_to_emission(persondata, temp, freq=120)
CO2rates <- unique(emissions$nadj_CO2rate)

# Now we have CO2 rates for each time point in our simulation in ug/s
# Let's convert back to L/min (see persondata_to_emission.R for justification of conversions)
emissions$nadj_CO2rate_lmin <- emissions$nadj_CO2rate / 1.965 / .0046 / (8.314*(273.15+temp)/101.325) / 1000 * 60

CO2rates_lmin <- unique(emissions$nadj_CO2rate_lmin)

# emissions$naj_CO2rate_ls holds n*Gp at each time point
# CO2rates_ls holds the unique values of n*Gp
# if you want to use with a method that takes n, use this value for Gp and set n=1


# let's add n*Gp and time to our simulated data
simulated.dat$nadj_CO2rate_lmin <- emissions$nadj_CO2rate_lmin
simulated.dat$time <- as.POSIXct.numeric(emissions$time*3600, origin="1970-01-01", tz="UTC")

#Prep for calling secant_main function
n = matrix(c(0,15,0,15,0,0,2,0,2,0), 5,2)
Gp = matrix(c(Gp_rate(16.00 / 24), Gp_rate(11.96 / 24)), 5, 2, byrow = TRUE)
V = rep(volume, 5)
n_change = simulated.dat$time[c(1,
                                which(simulated.dat$time == 8*3600),
                                which(simulated.dat$time == 12*3600),
                                which(simulated.dat$time == 13*3600),
                                which(simulated.dat$time == 17*3600))]



#Lets call our secant_main function
#First, use first pass values. Gp estimate using Gp_rate
output_sim_1 = secant_main(simulated.dat$time,
                     simulated.dat$CO2,
                     NA,
                     n,
                     Gp,
                     V,
                     n_change,
                     )

#Second, use recomendation from earlier code - use n = 1 and use values from emissions$nadj_CO2rate_lmin
output_sim_2 = secant_main(simulated.dat$time,
                      simulated.dat$CO2,
                      NA,
                      matrix(1,5,1),
                      c(0,7.128,0,7.290,0),
                      V,
                      n_change,
                      )
#Look at how much we need to reduce Gp by to get an answer close to the input Air Exchange Rate of .75
output_sim_3 = secant_main(simulated.dat$time,
                       simulated.dat$CO2,
                       NA,
                       n,
                       Gp/2.5,
                       V,
                       n_change,
)


#Try using values from the 1.4 met table in the main paper
output_sim_4 = secant_main(simulated.dat$time,
                       simulated.dat$CO2,
                       NA,
                       n,
                       matrix(c(0.471, .2), 5, 2, byrow = TRUE),
                       V,
                       n_change,
)



output_sim_df = data.frame("Output 1" = c(output_sim_1$summary_raw[4], output_sim_1$summary_interval[4]),
                           "Output 2" = c(output_sim_2$summary_raw[4], output_sim_2$summary_interval[4]),
                           "Output 4" = c(output_sim_4$summary_raw[4], output_sim_4$summary_interval[4]),
                           "Output 3 - Low Gp Value" = c(output_sim_3$summary_raw[4], output_sim_3$summary_interval[4]))

rownames(output_sim_df) = c("Raw Estimate", "Interval Estimate")


output_sim_df

#Seems like we are really over-estimating the air exchange rate of simulated data.

```

```{r}
#Lets estimate on our real data

data_1 = readxl::read_excel("C:\\Tom Files\\CESM MS\\Fall 2023\\BIOSTAT 615\\Package files for analysis\\Aranet4 0C1B8_2023-11-15T18_47_56-0500 (1).xlsx")
#Convert to date time using POSIXct
data_1[,1] = as.POSIXct(data_1$`Time(dd/mm/yyyy)`, format = "%j/%m/%Y %I:%M:%S %p")


#Lets prepare for the function call
#Assume that n is constant
n = 5
#There were only adults
Gp = Gp_rate(16.00 / 24)
#Room volume is the following:
room_length = 378 * 0.0254
room_width = 321 * 0.0254
room_height = 114 * 0.0254
room_volume = room_length * room_width * room_height


#Lets get outputdata for n = 1, n = 3, and n = 5

output_data_1 = secant_main(data_1$`Time(dd/mm/yyyy)`,
                            data_1$`Carbon dioxide(ppm)`,
                            NA,
                            1,
                            Gp,
                            room_volume,
                            NA,
                            quant_cutoff = 0.7)

output_data_3 = secant_main(data_1$`Time(dd/mm/yyyy)`,
                            data_1$`Carbon dioxide(ppm)`,
                            NA,
                            3,
                            Gp,
                            room_volume,
                            NA,
                            quant_cutoff = 0.7)

output_data_5 = secant_main(data_1$`Time(dd/mm/yyyy)`,
                            data_1$`Carbon dioxide(ppm)`,
                            NA,
                            5,
                            Gp,
                            room_volume,
                            NA,
                            quant_cutoff = 0.7)

#I am going to manually remove rows from the output that are not between 9 am and 5pm. We will assume that
#There are not individuals in the building outside of working hours

#Normally, there are between 3 - 5 people in that part of the lab. Based on these results, the Air Exchange Rate
#can be estimated to be between 4 and 6 air exchanges per hour, which is consistent with the minimum recommended
#values for the laboratory.
```

```{r}
#Replicate plots of simulated data calculations
#Vary the true ventilation rate
#Vary the variance of the simulated data
#Run 5 times for each condition
#200 simulations total


ventilation_values = seq(0.01, 1, length = 10)
variance_values = c(0.01, 0.1, 1, 2)

master_array = array(0, dim = c(5,10,4))

for (i in seq(1,length(variance_values))) { #length(variance_values)
  #each row corresponds to an iteration value, each column holds the values calculated for a given ventilation value
  average_matrix = matrix(0,5,10)
  for (j in seq(1, length(ventilation_values))){
    average_vals = c()
    for (k in seq(1,5)){
      # simulating data


      # Let's start with "person data"

      # simulated data for testing
      # consider a 24 hour time period, starting at midnight and running until the following midnight
      # We have 17 people enter at 8 am, leave for one hour at noon, and leave for the day at 5 pm
      # 2 adults and 15 children 
      persondata <- data.frame(
        time = c(0, 8, 8, 12, 12, 13, 13, 17, 24),
        n = c(0, 15, 2, 0, 0, 15, 2, 0, 0),
        age = c(0, 8, 30, 8, 30, 8, 30, 0, 0),
        gender = rep(NA, 9),
        MET = c(NA, 3, 1.8, 3, 1.8, 3, 2, NA, NA),
        CO2rate = rep(NA, 9)
      )

      volume=500
      envCO2=400
      temp=25
      Q= ventilation_values[j] # .1*3600/500 = .72 Air exchanges /hr
      var = variance_values[i] #Variance parameter for CO2 readings

      # Let's simulate data:
      simulated.dat <- simulateData(persondata=persondata,
                                    volume=volume,
                                    ventilation_rate=Q,
                                    CO2var=var, 
                                    freq=120)

      # Let's get Gp values for each time point in our simulation
      emissions <- persondata_to_emission(persondata, temp, freq=120)
      CO2rates <- unique(emissions$nadj_CO2rate)

      # Now we have CO2 rates for each time point in our simulation in ug/s
      # Let's convert back to L/min (see persondata_to_emission.R for justification of conversions)
      emissions$nadj_CO2rate_lmin <- emissions$nadj_CO2rate / 1.965 / .0046 / (8.314*(273.15+temp)/101.325) / 1000 * 60

      CO2rates_lmin <- unique(emissions$nadj_CO2rate_lmin)

      # emissions$naj_CO2rate_ls holds n*Gp at each time point
      # CO2rates_ls holds the unique values of n*Gp 
      # if you want to use with a method that takes n, use this value for Gp and set n=1 


      # let's add n*Gp and time to our simulated data
      simulated.dat$nadj_CO2rate_lmin <- emissions$nadj_CO2rate_lmin
      simulated.dat$time <- as.POSIXct.numeric(emissions$time*3600, origin="1970-01-01", tz="UTC")
      
      #Prep for calling secant_main function
      n = matrix(c(0,15,0,15,0,0,2,0,2,0), 5,2)
      Gp = matrix(c(Gp_rate(16.00 / 24), Gp_rate(11.96 / 24)), 5, 2, byrow = TRUE)
      V = rep(volume, 5)
      n_change = simulated.dat$time[c(1,
                                      which(simulated.dat$time == 8*3600),
                                      which(simulated.dat$time == 12*3600),
                                      which(simulated.dat$time == 13*3600),
                                      which(simulated.dat$time == 17*3600))]
      
      
      #Get our output
      output = secant_main(simulated.dat$time,
                          simulated.dat$CO2,
                          NA,
                          n,
                          Gp,
                          V,
                          n_change)
      
      #store average value into our list
      average_vals = c(average_vals, output$summary_raw[4])
    }
    
    #Append our average_vals vector to our matrix
    average_matrix[,j] = average_vals
  }
  #Rename the columns as the ventilation value and then append to our array
  colnames(average_matrix) = ventilation_values
  
  master_array[,,i] = average_matrix
}

dimnames(master_array)[3] = list(c('0.01', '0.1', '1', '2'))



```

